### ISSUE TITLE
It's really cool! 

### ISSUE THREAD

**Issue by sainisanjay** [XingangPan/DragGAN#1]
Does pre-trained model or code repo  is coming soon?

**Comment by XingangPan** [comment]
Hi @sainisanjay thanks for your interest. The code will be released soon, likely in the early/middle of June.

**Comment by ke1ne** [comment]
@XingangPan Do you plan to release the whole project's code or something like the GAN part? Thanks!

**Comment by ConatusBlues** [comment]
Looks really cool. Looking forward to test it when released. :)
Good luck with your project.
