### ISSUE TITLE
Unable to use my own images?

### ISSUE THREAD

**Issue by chrisbward** [XingangPan/DragGAN#100]
Hi, I don't seem to be able to find an upload for images - only when editing and resetting the mask am I able to drop a file in the Gradio demo, but this is immediately reset to the image for the weight when adding points?

**Comment by chrisbward** [comment]
I missed this in the docs, sorry;
```
This GUI supports editing GAN-generated images. To edit a real image, you need to first perform GAN inversion using tools like [PTI](https://github.com/danielroich/PTI). Then load the new latent code and model weights to the GUI.
```

**Comment by Pawandeep-prog** [comment]
here is step by step video guide [yt video](https://youtu.be/viWiOC1Mikw)

**Comment by limumua** [comment]
> 我在文档中错过了这一点，抱歉；
> 
> ```
> This GUI supports editing GAN-generated images. To edit a real image, you need to first perform GAN inversion using tools like [PTI](https://github.com/danielroich/PTI). Then load the new latent code and model weights to the GUI.
> ```

hello，I still don't quite understand how to do it. Can you tell me the specific steps? Thank you very much

**Comment by Pawandeep-prog** [comment]
@limumua you will need to have model weights and w_pivot file. You can get that from pti repo by uploading your custom image and run their code.
Once have those convert model weights to pickle format.
Then load that w_pivot and model weights in drag gan repo.

don't want to spam but this video can guide you : https://youtu.be/viWiOC1Mikw

**Comment by limumua** [comment]
> @limumua you will need to have model weights and w_pivot file. You can get that from pti repo by uploading your custom image and run their code. Once have those convert model weights to pickle format. Then load that w_pivot and model weights in drag gan repo.
> 
> don't want to spam but this video can guide you : https://youtu.be/viWiOC1Mikw

Thank you very much :). I will try it out!
