### ISSUE TITLE
Cudatoolkit issues

### ISSUE THREAD

**Issue by omarirfa** [XingangPan/DragGAN#128]
Has anyone faced the issue for cudatoolkit on windows using conda? I get this error: 

![image](https://github.com/XingangPan/DragGAN/assets/61637151/a0c1cb71-c50a-4abc-8c22-a7e8b9d7e70d)

Do I need to download cudatoolkit from [Nvidia](https://developer.nvidia.com/cuda-downloads) manually?

**Comment by PDillis** [comment]
Set the `CUDA_HOME` variable in the PATH. In Windows you just look for Path in the serach bar and you'll get to System Properties, click on Environment Variables and you can add a New System variable as `CUDA_HOME` and set it to `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8` (this is my specific case, you should see where you have CUDA installed). 

In Ubuntu it's a bit easier, as you simply set it like so in the command line: `export CUDA_HOME=/usr/local/cuda-X.X` (with whichever version of CUDA you have, assuming that's where it's installed).

**Comment by omarirfa** [comment]
Thanks worked like a charm!
