### ISSUE TITLE
can i get the codee

### ISSUE THREAD

**Issue by ah-hilali** [XingangPan/DragGAN#15]
how to get the code ? is this opensource ?

**Comment by oahzuw** [comment]
read [README.md](https://github.com/XingangPan/DragGAN/blob/main/README.md)

**Comment by woctezuma** [comment]
- #5

**Comment by mehdynesmon** [comment]
Hi, I would like to give a try too.

**Comment by OFD16** [comment]
Code will be released in June. @mehdynesmon  check ReadME file

**Comment by RoamMate** [comment]
this a powerful technology

**Comment by Zeqiang-Lai** [comment]
Take a look of my implementation, https://github.com/Zeqiang-Lai/DragGAN
