### ISSUE TITLE
Question: Is this standalone? 

### ISSUE THREAD

**Issue by JemiloII** [XingangPan/DragGAN#22]
Wondering if this is standalone or if i have to use automatic1111. I have a tool I've built from scratch and would love to include this in it. I'll contribute back to the project as well. Amazing work~

**Comment by pblanco-dekalabs** [comment]
I would love to see it integrated in Automatic1111's web UI, for me would be easier. (IDK if can be done)

**Comment by JemiloII** [comment]
@pblanco-dekalabs, someone will get it to automatic1111 sooner than later, most likely. I don't like automatic1111; feels like it hurts the community to be able to make new tools.
