### ISSUE TITLE
not funtion

### ISSUE THREAD

**Issue by mary4500** [XingangPan/DragGAN#24]
not funtion!

**Comment by LeonKnook** [comment]
same here I get: 
ModuleNotFoundError: No module named 'torch'

**Comment by LeonKnook** [comment]
C:\Users\Leon\Downloads\DragGAN-main\DragGAN-main>python gradio_app.py
Traceback (most recent call last):
  File "C:\Users\Leon\Downloads\DragGAN-main\DragGAN-main\gradio_app.py", line 1, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'

**Comment by LeonKnook** [comment]
C:\Users\Leon\Downloads\DragGAN-main\DragGAN-main>python --version
Python 3.11.3
