### ISSUE TITLE
Any update for DragGAN code? It's almost July Now!

### ISSUE THREAD

**Issue by kanseaveg** [XingangPan/DragGAN#30]

**Comment by Lurk3r** [comment]
你好，盛仔已经收到你的来信，我将尽快回复并与你取得联系，非常感谢。

**Comment by Joeking-around** [comment]
你好，我是胡程乔，你的来件已收到，谢谢复制搜索

**Comment by Xparn00** [comment]
Bonsoir, bientôt juillet nous attendons avec impatience 🙏

**Comment by seghier** [comment]
Search in Github you will find some versions
https://github.com/Zeqiang-Lai/DragGAN
https://github.com/JiauZhang/DragGAN
