### ISSUE TITLE
run in colab error

### ISSUE THREAD

**Issue by safehumeng** [XingangPan/DragGAN#408]
![image](https://github.com/XingangPan/DragGAN/assets/16226299/b28082e5-2b22-4c30-8c1b-258b5b49af79)

**Comment by rajnish159** [comment]
I solved this problem!

pip install draggan
!pip3 install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/nightly/cu118/torch_nightly.html
pip install Pillow==9.5.0
After installing the above three software packages, you can run DragGAN normally.
 this is properly working

**Comment by safehumeng** [comment]
> I solved this problem!
> 
> pip install draggan !pip3 install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/nightly/cu118/torch_nightly.html pip install Pillow==9.5.0 After installing the above three software packages, you can run DragGAN normally. this is properly working

thanks! It's works

**Comment by m-ali-awan** [comment]
Thanks alot @rajnish159 

Also, for using with custom Image, I am experiencing after doing PTI part, my inverted image is totally noise. Has anyon experienced this?

I followed this colab:

https://colab.research.google.com/drive/1aZW21clDPWLvwBnaQG5Xcpc_U-8zy3ow?usp=sharing

Thanks for any help
