### ISSUE TITLE
colab version please！

### ISSUE THREAD

**Issue by skyeKing** [XingangPan/DragGAN#48]

**Comment by Ailyth99** [comment]
try this  colab ver
https://colab.research.google.com/drive/1ysGkcpJsdw1TGN0wiW45xz5u1_qNQ0m_#scrollTo=7HVBTrLjNCk7

**Comment by x18-1** [comment]
how can i upload my own picture

**Comment by nikunjalamsal** [comment]
Its awesome. @Ailyth99
