### ISSUE TITLE
Error: ModuleNotFoundError: No module named 'imgui'

### ISSUE THREAD

**Issue by enriquemorenotent** [XingangPan/DragGAN#51]
I created a new coda env with Python 3.11 and installed the models, but when I execute the GUI, I encounter this error:

```
➜ conda create --name dragcan python=3.11

➜ pip install -r requirements.txt                          

➜ sh scripts/gui.sh  
Traceback (most recent call last):
  File "/home/dbugger/projects/ai/DragGAN/visualizer_drag.py", line 15, in <module>
    import imgui
ModuleNotFoundError: No module named 'imgui'
                
```

**Comment by quanjunjie531** [comment]
pip install imgui 
you should see the enviroment.txt first.
check your all module version is OK.

**Comment by enriquemorenotent** [comment]
This is my requirements.txt

```
➜ cat requirements.txt 
torch
torchvision
Ninja
gradio
huggingface_hub
hf_transfer%      
```

**Comment by quanjunjie531** [comment]
not only requirements.txt, you can see the enviroment.txt .

**Comment by enriquemorenotent** [comment]
There is no `enviroment.txt`. Just an `environment.yml`. Is it the same?

I am a python newbie, so I am not sure what these files are for. I assumed that `requirements.txt` is a kind of `package.json`. I have no idea what `environment.yml` is for...

**Comment by quanjunjie531** [comment]
yap,sorry , my falt, 
look the environment.yml .

**Comment by enriquemorenotent** [comment]
Ok, I see. I didnt know that environment.yml was meant to configure a conda env for me. Thanks for the lesson! :)

**Comment by Lling00** [comment]
![image](https://github.com/XingangPan/DragGAN/assets/48402714/5aaf68ab-51c6-4b16-bc0b-b7d3d34a1fdc)
It's just as good as reinstalling it.
