### ISSUE TITLE
NameError: name 'inverse_image' is not defined

### ISSUE THREAD

**Issue by alienhd** [XingangPan/DragGAN#53]
When trying to import a custom image file, I always receive the error message: 

```
File "PathtoDragGAN\draggan\web.py", line 183, in on_image_change
    result = inverse_image(
NameError: name 'inverse_image' is not defined
```

**Comment by ulucsahin** [comment]
Have you been able to solve this issue?

**Comment by alienhd** [comment]
The creator wrote:

1.1.5 has a major update which makes old inverse_image incompatible. I am still working on the new one. If you want to try custom image now. Downgrade to 1.1.0

pip install draggan==1.1.0
