### ISSUE TITLE
OSError: cannot open resource

### ISSUE THREAD

**Issue by trueto** [XingangPan/DragGAN#80]
File under cache_dir (./checkpoints):
['stylegan2-afhqcat-512x512.pkl', 'stylegan2-cat-config-f.pkl', 'stylegan2-ffhq-512x512.pkl', 'stylegan2_dogs_1024_pytorch.pkl', 'stylegan2_lions_512_pytorch.pkl', 'stylegan2_horses_256_pytorch.pkl', 'stylegan2-car-config-f.pkl', 'stylegan2_elephants_512_pytorch.pkl']
Valid checkpoint file:
{'stylegan2-afhqcat-512x512': './checkpoints/stylegan2-afhqcat-512x512.pkl', 'stylegan2-cat-config-f': './checkpoints/stylegan2-cat-config-f.pkl', 'stylegan2-ffhq-512x512': './checkpoints/stylegan2-ffhq-512x512.pkl', 'stylegan2_dogs_1024_pytorch': './checkpoints/stylegan2_dogs_1024_pytorch.pkl', 'stylegan2_lions_512_pytorch': './checkpoints/stylegan2_lions_512_pytorch.pkl', 'stylegan2_horses_256_pytorch': './checkpoints/stylegan2_horses_256_pytorch.pkl', 'stylegan2-car-config-f': './checkpoints/stylegan2-car-config-f.pkl', 'stylegan2_elephants_512_pytorch': './checkpoints/stylegan2_elephants_512_pytorch.pkl'}
Loading "./checkpoints/stylegan2_lions_512_pytorch.pkl"... Done.
()
{'z_dim': 512, 'c_dim': 0, 'w_dim': 512, 'img_resolution': 512, 'img_channels': 3, 'mapping_kwargs': {'num_layers': 8, 'embed_features': None, 'layer_features': None, 'activation': 'lrelu', 'lr_multiplier': 0.01, 'w_avg_beta': 0.995}, 'synthesis_kwargs': {'channel_base': 32768, 'channel_max': 512, 'num_fp16_res': 0, 'conv_clamp': None, 'architecture': 'skip', 'resample_filter': [1, 3, 3, 1], 'use_noise': True, 'activation': 'lrelu'}}
Setting up PyTorch plugin "bias_act_plugin"... Done.
Setting up PyTorch plugin "upfirdn2d_plugin"... Done.
Traceback (most recent call last):
  File "/content/DragGAN/visualizer_drag_gradio.py", line 200, in <module>
    global_state = init_images(global_state)
  File "/content/DragGAN/visualizer_drag_gradio.py", line 91, in init_images
    add_watermark_np(np.array(init_image)))
  File "/content/DragGAN/viz/renderer.py", line 53, in add_watermark_np
    font = ImageFont.truetype('arial.ttf', round(25/512*image.size[0]))
  File "/usr/local/lib/python3.10/dist-packages/PIL/ImageFont.py", line 855, in truetype
    return freetype(font)
  File "/usr/local/lib/python3.10/dist-packages/PIL/ImageFont.py", line 852, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/usr/local/lib/python3.10/dist-packages/PIL/ImageFont.py", line 211, in __init__
    self.font = core.getfont(
OSError: cannot open resource

when i "!python /content/DragGAN/visualizer_drag_gradio.py" on cloab,what's wrong!

**Comment by quanjunjie531** [comment]
its my solution,you can try it.
download the arial.ttf,
mkdir /usr/share/fonts/truetype/arial
mv arial.ttf /usr/share/fonts/truetype/arial
chmod 744 /usr/share/fonts/truetype/arial/arial.ttf
mkfontscale
mkfontdir
fc-cache -fv

edit renderer.py
ImageFont.truetype('arial.ttf', round(25/512*image.size[0])) => ImageFont.truetype('arial/arial.ttf', round(25/512*image.size[0]))

**Comment by trueto** [comment]
Fixed!
here is the cloab version!
[https://colab.research.google.com/drive/1URdYaO7FyBuNw1bqabZ9ozhuX3y_ntgV?usp=sharing](url)
