### ISSUE TITLE
Provide an example of latent as input.

### ISSUE THREAD

**Issue by quqixun** [XingangPan/DragGAN#89]
Could you please provide an example of latent for testing?

**Comment by Pawandeep-prog** [comment]
Try this

https://youtu.be/viWiOC1Mikw

**Comment by quqixun** [comment]
Thanks. It is a wonderful demo.
I will also try [hyperstyle](https://github.com/yuval-alaluf/hyperstyle).

**Comment by MidnightFiend** [comment]
> Thanks. It is a wonderful demo. I will also try [hyperstyle](https://github.com/yuval-alaluf/hyperstyle).

Has the idea run its course？
